# Generated by Django 4.1.1 on 2022-10-12 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
