# Generated by Django 4.1.1 on 2022-10-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBfinder', '0002_alter_course_catalog_number_alter_course_component_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='friends',
            field=models.ManyToManyField(blank=True, to='SBfinder.userinfo'),
        ),
    ]
