# Generated by Django 4.1.1 on 2022-11-05 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBfinder', '0004_friend_request'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Session',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('time', models.TimeField()),
                ('users', models.ManyToManyField(to='SBfinder.userinfo')),
            ],
        ),
    ]
