# Generated by Django 4.1.1 on 2022-11-05 18:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SBfinder', '0005_study_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_session',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date proposed'),
            preserve_default=False,
        ),
    ]
