# Generated by Django 4.1.1 on 2022-11-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SBfinder', '0006_study_session_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Study_Session_Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('study_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='SBfinder.study_session')),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_user_ss', to='SBfinder.userinfo')),
            ],
        ),
    ]
