# Generated by Django 4.1.1 on 2022-11-05 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SBfinder', '0007_study_session_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_session_request',
            name='study_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SBfinder.study_session'),
        ),
    ]
