# Generated by Django 4.1.1 on 2022-11-09 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SBfinder', '0008_alter_study_session_request_study_session'),
    ]

    operations = [
        migrations.AlterField(
            model_name='study_session',
            name='time',
            field=models.DateTimeField(verbose_name='time proposed'),
        ),
    ]
