# Generated by Django 4.1.1 on 2022-11-09 18:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SBfinder', '0010_alter_study_session_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='study_session',
            name='exact_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Exact time proposed'),
            preserve_default=False,
        ),
    ]
