# Generated by Django 4.1.1 on 2022-11-10 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBfinder', '0012_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='study_session',
            options={'ordering': ['exact_time']},
        ),
    ]
