# Generated by Django 4.1.1 on 2022-11-10 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SBfinder', '0013_alter_study_session_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['time']},
        ),
    ]
